#!/bin/sh

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if [ $# -eq 0 ]
then
    printf 'Usage: %s DEVICE [DEVICE...]\n' "${0##*/}">&2
fi
for dev in "$@"
do
    dev=$(readlink -f "$dev")
    dev=${dev#/dev/}
    syspath="/sys/block/$dev/device"
    stat "$syspath/delete" > /dev/null
    printf '%s\n' "$syspath"
    echo 1 > "$syspath/delete"
done

# vim:ts=4 sts=4 sw=4 et
